// <auto-generated />
using System;
using CongestionTaxCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CongestionTaxCalculator.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxDayOffPeakSeason")
                        .HasColumnType("int");

                    b.Property<int>("MaxDayPeakSeason")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PeakSeason")
                        .HasColumnType("bit");

                    b.Property<bool>("SingleChargeRule")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxDayOffPeakSeason = 60,
                            MaxDayPeakSeason = 60,
                            Name = "Gothenburg",
                            PeakSeason = false,
                            SingleChargeRule = true
                        },
                        new
                        {
                            Id = 2,
                            MaxDayOffPeakSeason = 105,
                            MaxDayPeakSeason = 135,
                            Name = "Stockholm",
                            PeakSeason = true,
                            SingleChargeRule = false
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.FreeOfChargeDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("FreeOfChargeDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Date = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Date = new DateTime(2013, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Date = new DateTime(2013, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Date = new DateTime(2013, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Date = new DateTime(2013, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Date = new DateTime(2013, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Date = new DateTime(2013, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Date = new DateTime(2013, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            Date = new DateTime(2013, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CityId = 1,
                            Date = new DateTime(2013, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CityId = 1,
                            Date = new DateTime(2013, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CityId = 1,
                            Date = new DateTime(2013, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CityId = 1,
                            Date = new DateTime(2013, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CityId = 1,
                            Date = new DateTime(2013, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CityId = 1,
                            Date = new DateTime(2013, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CityId = 1,
                            Date = new DateTime(2013, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CityId = 1,
                            Date = new DateTime(2013, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CityId = 1,
                            Date = new DateTime(2013, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CityId = 1,
                            Date = new DateTime(2013, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CityId = 1,
                            Date = new DateTime(2013, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CityId = 1,
                            Date = new DateTime(2013, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CityId = 1,
                            Date = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            CityId = 1,
                            Date = new DateTime(2013, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            CityId = 2,
                            Date = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            CityId = 2,
                            Date = new DateTime(2013, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            CityId = 2,
                            Date = new DateTime(2013, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            CityId = 2,
                            Date = new DateTime(2013, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            CityId = 2,
                            Date = new DateTime(2013, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            CityId = 2,
                            Date = new DateTime(2013, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            CityId = 2,
                            Date = new DateTime(2013, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            CityId = 2,
                            Date = new DateTime(2013, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            CityId = 2,
                            Date = new DateTime(2013, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            CityId = 2,
                            Date = new DateTime(2013, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            CityId = 2,
                            Date = new DateTime(2013, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            CityId = 2,
                            Date = new DateTime(2013, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            CityId = 2,
                            Date = new DateTime(2013, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            CityId = 2,
                            Date = new DateTime(2013, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            CityId = 2,
                            Date = new DateTime(2013, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            CityId = 2,
                            Date = new DateTime(2013, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            CityId = 2,
                            Date = new DateTime(2013, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            CityId = 2,
                            Date = new DateTime(2013, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            CityId = 2,
                            Date = new DateTime(2013, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            CityId = 2,
                            Date = new DateTime(2013, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            CityId = 2,
                            Date = new DateTime(2013, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            CityId = 2,
                            Date = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 101,
                            CityId = 2,
                            Date = new DateTime(2013, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.PeakDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeakBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeakEnd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PeakDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 2,
                            PeakBegin = new DateTime(2013, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeakEnd = new DateTime(2013, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            PeakBegin = new DateTime(2013, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeakEnd = new DateTime(2013, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.TaxAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("PeakSeason")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TaxAmounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 0, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 9,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 6, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 16,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 6, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 22,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 7, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 16,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 8, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Amount = 9,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 8, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Amount = 16,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 15, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 15, 30, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            Amount = 22,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 15, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Amount = 16,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 17, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Amount = 9,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 18, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            Amount = 0,
                            CityId = 1,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 18, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            Amount = 0,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 0, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            Amount = 15,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 6, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            Amount = 30,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 6, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            Amount = 45,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 7, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            Amount = 30,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 8, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            Amount = 20,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 9, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            Amount = 11,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 9, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            Amount = 20,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 15, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 15, 30, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            Amount = 30,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 15, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            Amount = 45,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 16, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 17, 30, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            Amount = 30,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 17, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            Amount = 20,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 18, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            Amount = 0,
                            CityId = 2,
                            PeakSeason = true,
                            TimeIn = new TimeSpan(0, 18, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            Amount = 0,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 0, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            Amount = 15,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 6, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 27,
                            Amount = 25,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 6, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 28,
                            Amount = 35,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 7, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 29,
                            Amount = 25,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 8, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 30,
                            Amount = 15,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 9, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = 31,
                            Amount = 11,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 9, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 32,
                            Amount = 15,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 15, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 15, 30, 0, 0)
                        },
                        new
                        {
                            Id = 33,
                            Amount = 25,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 15, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 34,
                            Amount = 35,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 16, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 17, 30, 0, 0)
                        },
                        new
                        {
                            Id = 35,
                            Amount = 25,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 17, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 36,
                            Amount = 15,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 18, 0, 0, 0),
                            TimeOut = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 37,
                            Amount = 0,
                            CityId = 2,
                            PeakSeason = false,
                            TimeIn = new TimeSpan(0, 18, 30, 0, 0),
                            TimeOut = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.FreeOfChargeDay", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.PeakDay", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Models.Entities.TaxAmount", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
