using CongestionTaxCalculator.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;

namespace CongestionTaxCalculator.Data.Configuration
{
    public class FreeOfChargeDayConfiguration : IEntityTypeConfiguration<FreeOfChargeDay>
    {
        public void Configure(EntityTypeBuilder<FreeOfChargeDay> builder)
        {
            builder.HasData(
                new FreeOfChargeDay { Id = 1, CityId = 1, Date = new DateTime(2013, 1, 1) },
                new FreeOfChargeDay { Id = 2, CityId = 1, Date = new DateTime(2013, 1, 5) },
                new FreeOfChargeDay { Id = 3, CityId = 1, Date = new DateTime(2013, 1, 6) },
                new FreeOfChargeDay { Id = 4, CityId = 1, Date = new DateTime(2013, 3, 28) },
                new FreeOfChargeDay { Id = 5, CityId = 1, Date = new DateTime(2013, 3, 29) },
                new FreeOfChargeDay { Id = 6, CityId = 1, Date = new DateTime(2013, 3, 30) },
                new FreeOfChargeDay { Id = 7, CityId = 1, Date = new DateTime(2013, 3, 31) },
                new FreeOfChargeDay { Id = 8, CityId = 1, Date = new DateTime(2013, 4, 1) },
                new FreeOfChargeDay { Id = 9, CityId = 1, Date = new DateTime(2013, 4, 30) },
                new FreeOfChargeDay { Id = 10, CityId = 1, Date = new DateTime(2013, 5, 1) },
                new FreeOfChargeDay { Id = 11, CityId = 1, Date = new DateTime(2013, 5, 9) },
                new FreeOfChargeDay { Id = 12, CityId = 1, Date = new DateTime(2013, 5, 18) },
                new FreeOfChargeDay { Id = 13, CityId = 1, Date = new DateTime(2013, 5, 19) },
                new FreeOfChargeDay { Id = 14, CityId = 1, Date = new DateTime(2013, 6, 6) },
                new FreeOfChargeDay { Id = 15, CityId = 1, Date = new DateTime(2013, 6, 21) },
                new FreeOfChargeDay { Id = 16, CityId = 1, Date = new DateTime(2013, 6, 22) },
                new FreeOfChargeDay { Id = 17, CityId = 1, Date = new DateTime(2013, 11, 1) },
                new FreeOfChargeDay { Id = 18, CityId = 1, Date = new DateTime(2013, 11, 2) },
                new FreeOfChargeDay { Id = 19, CityId = 1, Date = new DateTime(2013, 12, 24) },
                new FreeOfChargeDay { Id = 20, CityId = 1, Date = new DateTime(2013, 12, 25) },
                new FreeOfChargeDay { Id = 21, CityId = 1, Date = new DateTime(2013, 12, 6) },
                new FreeOfChargeDay { Id = 22, CityId = 1, Date = new DateTime(2013, 12, 31) },

                new FreeOfChargeDay { Id = 23, CityId = 1, Date = new DateTime(2013, 7, 1) },
                new FreeOfChargeDay { Id = 24, CityId = 1, Date = new DateTime(2013, 7, 2) },
                new FreeOfChargeDay { Id = 25, CityId = 1, Date = new DateTime(2013, 7, 3) },
                new FreeOfChargeDay { Id = 26, CityId = 1, Date = new DateTime(2013, 7, 4) },
                new FreeOfChargeDay { Id = 27, CityId = 1, Date = new DateTime(2013, 7, 5) },
                new FreeOfChargeDay { Id = 28, CityId = 1, Date = new DateTime(2013, 7, 6) },
                new FreeOfChargeDay { Id = 29, CityId = 1, Date = new DateTime(2013, 7, 7) },
                new FreeOfChargeDay { Id = 30, CityId = 1, Date = new DateTime(2013, 7, 8) },
                new FreeOfChargeDay { Id = 31, CityId = 1, Date = new DateTime(2013, 7, 9) },
                new FreeOfChargeDay { Id = 32, CityId = 1, Date = new DateTime(2013, 7, 10) },
                new FreeOfChargeDay { Id = 33, CityId = 1, Date = new DateTime(2013, 7, 11) },
                new FreeOfChargeDay { Id = 34, CityId = 1, Date = new DateTime(2013, 7, 12) },
                new FreeOfChargeDay { Id = 35, CityId = 1, Date = new DateTime(2013, 7, 13) },
                new FreeOfChargeDay { Id = 36, CityId = 1, Date = new DateTime(2013, 7, 14) },
                new FreeOfChargeDay { Id = 37, CityId = 1, Date = new DateTime(2013, 7, 15) },
                new FreeOfChargeDay { Id = 38, CityId = 1, Date = new DateTime(2013, 7, 16) },
                new FreeOfChargeDay { Id = 39, CityId = 1, Date = new DateTime(2013, 7, 17) },
                new FreeOfChargeDay { Id = 40, CityId = 1, Date = new DateTime(2013, 7, 18) },
                new FreeOfChargeDay { Id = 41, CityId = 1, Date = new DateTime(2013, 7, 19) },
                new FreeOfChargeDay { Id = 42, CityId = 1, Date = new DateTime(2013, 7, 20) },
                new FreeOfChargeDay { Id = 43, CityId = 1, Date = new DateTime(2013, 7, 21) },
                new FreeOfChargeDay { Id = 44, CityId = 1, Date = new DateTime(2013, 7, 22) },
                new FreeOfChargeDay { Id = 45, CityId = 1, Date = new DateTime(2013, 7, 23) },
                new FreeOfChargeDay { Id = 46, CityId = 1, Date = new DateTime(2013, 7, 24) },
                new FreeOfChargeDay { Id = 47, CityId = 1, Date = new DateTime(2013, 7, 25) },
                new FreeOfChargeDay { Id = 48, CityId = 1, Date = new DateTime(2013, 7, 26) },
                new FreeOfChargeDay { Id = 49, CityId = 1, Date = new DateTime(2013, 7, 27) },
                new FreeOfChargeDay { Id = 50, CityId = 1, Date = new DateTime(2013, 7, 28) },
                new FreeOfChargeDay { Id = 51, CityId = 1, Date = new DateTime(2013, 7, 29) },
                new FreeOfChargeDay { Id = 52, CityId = 1, Date = new DateTime(2013, 7, 30) },
                new FreeOfChargeDay { Id = 53, CityId = 1, Date = new DateTime(2013, 7, 31) },

                new FreeOfChargeDay { Id = 54, CityId = 2, Date = new DateTime(2013, 1, 1) },
                new FreeOfChargeDay { Id = 55, CityId = 2, Date = new DateTime(2013, 1, 5) },
                new FreeOfChargeDay { Id = 56, CityId = 2, Date = new DateTime(2013, 1, 6) },
                new FreeOfChargeDay { Id = 57, CityId = 2, Date = new DateTime(2013, 3, 28) },
                new FreeOfChargeDay { Id = 58, CityId = 2, Date = new DateTime(2013, 3, 29) },
                new FreeOfChargeDay { Id = 59, CityId = 2, Date = new DateTime(2013, 3, 30) },
                new FreeOfChargeDay { Id = 60, CityId = 2, Date = new DateTime(2013, 3, 31) },
                new FreeOfChargeDay { Id = 61, CityId = 2, Date = new DateTime(2013, 4, 1) },
                new FreeOfChargeDay { Id = 62, CityId = 2, Date = new DateTime(2013, 4, 30) },
                new FreeOfChargeDay { Id = 63, CityId = 2, Date = new DateTime(2013, 5, 1) },
                new FreeOfChargeDay { Id = 64, CityId = 2, Date = new DateTime(2013, 5, 9) },
                new FreeOfChargeDay { Id = 65, CityId = 2, Date = new DateTime(2013, 5, 18) },
                new FreeOfChargeDay { Id = 66, CityId = 2, Date = new DateTime(2013, 5, 19) },
                new FreeOfChargeDay { Id = 67, CityId = 2, Date = new DateTime(2013, 6, 6) },
                new FreeOfChargeDay { Id = 68, CityId = 2, Date = new DateTime(2013, 6, 21) },
                new FreeOfChargeDay { Id = 69, CityId = 2, Date = new DateTime(2013, 6, 22) },
                new FreeOfChargeDay { Id = 70, CityId = 2, Date = new DateTime(2013, 11, 1) },
                new FreeOfChargeDay { Id = 71, CityId = 2, Date = new DateTime(2013, 11, 2) },
                new FreeOfChargeDay { Id = 72, CityId = 2, Date = new DateTime(2013, 12, 24) },
                new FreeOfChargeDay { Id = 73, CityId = 2, Date = new DateTime(2013, 12, 25) },
                new FreeOfChargeDay { Id = 74, CityId = 2, Date = new DateTime(2013, 12, 6) },
                new FreeOfChargeDay { Id = 75, CityId = 2, Date = new DateTime(2013, 12, 31) },

                new FreeOfChargeDay { Id = 76, CityId = 2, Date = new DateTime(2013, 7, 6) },
                new FreeOfChargeDay { Id = 77, CityId = 2, Date = new DateTime(2013, 7, 7) },
                new FreeOfChargeDay { Id = 78, CityId = 2, Date = new DateTime(2013, 7, 8) },
                new FreeOfChargeDay { Id = 79, CityId = 2, Date = new DateTime(2013, 7, 9) },
                new FreeOfChargeDay { Id = 80, CityId = 2, Date = new DateTime(2013, 7, 10) },
                new FreeOfChargeDay { Id = 81, CityId = 2, Date = new DateTime(2013, 7, 11) },
                new FreeOfChargeDay { Id = 82, CityId = 2, Date = new DateTime(2013, 7, 12) },
                new FreeOfChargeDay { Id = 83, CityId = 2, Date = new DateTime(2013, 7, 13) },
                new FreeOfChargeDay { Id = 84, CityId = 2, Date = new DateTime(2013, 7, 14) },
                new FreeOfChargeDay { Id = 85, CityId = 2, Date = new DateTime(2013, 7, 15) },
                new FreeOfChargeDay { Id = 86, CityId = 2, Date = new DateTime(2013, 7, 16) },
                new FreeOfChargeDay { Id = 87, CityId = 2, Date = new DateTime(2013, 7, 17) },
                new FreeOfChargeDay { Id = 88, CityId = 2, Date = new DateTime(2013, 7, 18) },
                new FreeOfChargeDay { Id = 89, CityId = 2, Date = new DateTime(2013, 7, 19) },
                new FreeOfChargeDay { Id = 90, CityId = 2, Date = new DateTime(2013, 7, 20) },
                new FreeOfChargeDay { Id = 91, CityId = 2, Date = new DateTime(2013, 7, 21) },
                new FreeOfChargeDay { Id = 92, CityId = 2, Date = new DateTime(2013, 7, 22) },
                new FreeOfChargeDay { Id = 93, CityId = 2, Date = new DateTime(2013, 7, 23) },
                new FreeOfChargeDay { Id = 94, CityId = 2, Date = new DateTime(2013, 7, 24) },
                new FreeOfChargeDay { Id = 95, CityId = 2, Date = new DateTime(2013, 7, 25) },
                new FreeOfChargeDay { Id = 96, CityId = 2, Date = new DateTime(2013, 7, 26) },
                new FreeOfChargeDay { Id = 97, CityId = 2, Date = new DateTime(2013, 7, 27) },
                new FreeOfChargeDay { Id = 98, CityId = 2, Date = new DateTime(2013, 7, 28) },
                new FreeOfChargeDay { Id = 99, CityId = 2, Date = new DateTime(2013, 7, 29) },
                new FreeOfChargeDay { Id = 100, CityId = 2, Date = new DateTime(2013, 7, 30) },
                new FreeOfChargeDay { Id = 101, CityId = 2, Date = new DateTime(2013, 7, 31) }
            );
        }
    }
}
